[profile.default]
src = "src"
out = "out"
libs = ["lib"]

auto_detect_remappings = true # recursive auto-detection of remappings
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

[rpc_endpoints]
sepolia = "${ALCHEMY_SEPOLIA_RPC_URL}"

etherscan_api_key = "${ETHERSCAN_API_KEY}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
